### ISSUE TITLE
[Question] Information of how you test the hyperlolog implementation?

### ISSUE THREAD

**Issue by linearregression** [dialtr/libcount#11]
It will be very helpful if you can details how you test the accuracy of implementation. 
e.g. where those contents in RAW_ESTIMATE_DATA   comes from?
file: https://github.com/dialtr/libcount/blob/master/count/empirical_data.cc

I saw so many repo, they just throw in some toy examples as tests. I am highly suspicious some of the repos may be incorrect (e.g. saw some using vanilla random number generator).  
For this type of data-structure, it is not enough. So far I have not came across much literature out there to say so.

Asked you becasue I saw your name mentioned (Appendix to HyperLogLog in Practice: Algorithmic Engineering of a State of the Art Cardinality Estimation Algorithm) :

https://docs.google.com/document/d/1gyjfMHy43U9OWBXxfaeG-3MjGzejW1dlpyMwEYAAWEI/view?fullscreen&pref=2&pli=1#

**Comment by dialtr** [comment]
As the README indicates, I don't have proper tests at this time. I'm working to rectify this.

**Comment by dialtr** [comment]
My understanding is that the constants in RAW_ESTIMATE_DATA were the result of considerable empirical testing conducted by the original authors of the paper, who due to the nature of their work, likely have a vested interest in ensuring that the bias correction data is accurate.  For my implementation, I used the authors' data without changes.

While the alpha version of my implementation does not include an appropriate level of unit tests or certification tests at this time, I fully intend to implement a more complete suite. 

In order to confirm the estimate data, a certification test would need to construct data sets with varying, but known cardinalities. Those sets would then be counted using the implementation under test and the results compared to determine whether the bias correction data is accurate.  Considerable deviation between the counts would indicate a flaw in the bias correction data.

Those interested in assisting with the certification tests are welcome to contact me! My email address is included in the README.md file.

As a final note, I am not affiliated with the authors of the paper (other than having a shared interest in the HyperLogLog++ algorithm.) Any errors in my implementation are my own. Furthermore, as stated in the LICENSE.md file, this software is provided on an AS-IS basis.

**Comment by dialtr** [comment]
Just a quick update. With my most recent change, the raw ESTIMATE_DATA (now broken out separately in hll_data.cc / hll_data.h) is sorted so that estimate values increase monotonically with their array indices.  The corresponding bias values are stored in BIAS_DATA.

A certification test is forthcoming.

**Comment by dialtr** [comment]
You can now run:

   make certify

To perform a basic certification test that runs through an exhaustive series of counts at every precision level, reporting real vs. actual cardinalities and % error.
